baseURL: /
languageCode: en
title: Platform UI

enableRobotsTXT: true
disableAliases: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: dracula
    tabWidth: 2

taxonomies:
  category: category
  tags: tags

summaryLength: 30

menu:
  main:
  - identifier: docs
    name: Docs
    url: /docs/
  - identifier: icons
    name: Icons
    url: /icons/
  - identifier: examples
    name: Examples
    url: /examples/
  - identifier: portfolio
    parent: examples
    name: Portfolio
    url: /examples/portfolio/
  - identifier: ecommerce
    parent: examples
    name: Ecommerce
    url: /examples/ecommerce/
  - identifier: blog
    parent: examples
    name: Blog
    url: /examples/blog/
  - identifier: tutorials
    name: Tutorials
    url: /tutorials/
