baseURL: /
languageCode: en
title: Platform UI

enableRobotsTXT: true
disableAliases: true
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 2
    ordered: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: dracula
    tabWidth: 2

taxonomies:
  category: category
  tags: tags

summaryLength: 30

menu:
  main:
  - identifier: docs
    name: Docs
    url: /docs/
    weight: 1
  - identifier: icons
    name: Icons
    url: /icons/
    weight: 2
  - identifier: examples
    name: Examples
    url: /examples/
  - identifier: tutorials
    name: Tutorials
    url: /tutorials/
