environment:
  matrix:
    - nodejs_version: STABLE

install:
  - ps: Install-Product node $env:nodejs_version
  - choco install hugo-extended

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - hugo version

build_script:
  - ./build_appveyor.ps1

after_build:
  - ps: ./after_build.ps1
  - ls -l

notifications:
  - provider: GitHubPullRequest
    auth_token:
      secure: OoKsybfXrt38Y370sMRNScOqC2f9teNIbwTTol8zANmQpl91yBQNn4HC5woQZz9A
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})
    {{#failed}}
      <hr />
      {{#jobs}}
      <details>
      {{#compilationMessages}}
        {{category}}: {{message}}
      {{/compilationMessages}}
      </details>
      {{/jobs}}
    {{/failed}}"

cache:
  - '%TEMP%\hugo_cache'
  - node_modules -> package.json, package-lock.json

test: off

artifacts:
  - path: styleguide.zip
    name: Styleguide
    type: Zip

deploy:
  - provider: Environment
    name: Azure App Service Zip (Development)
    artifact: Styleguide
    slot: staging
    app_name: rim-platform-ui-east-dev
    on:
      branch: master
