name: Update Master

on: 
  pull_request_target:
    types:
      - closed
    branches: 
      - 'development'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: echo "✅ Checking out development."
    - name: checkout
      uses: actions/checkout@v3
    - name: Approve Pull Request
      uses: juliangruber/approve-pull-request-action@v1.1.1
      with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      number: 1
    - run: echo "🎯 Merging development into master."  
    - name: merge
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ github.token }}
        source_ref: 'development'
        target_branch: 'master'
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
    - run: echo "🥃 Workflow complete." 