# Merges [closed] PRs from development into master
name: PRs to development
on:
  push:
    branches: 
      - development
  pull_request:
    branches: 
      - development
    
jobs:
  merge-dev-into-master:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Merge dev -> master
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: master
        github_token: ${{ github.token }}

