# Merges [closed] PRs from development into master
name: PRs to development
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
    types: [closed]
jobs:
  merge-dev-into-master:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
