# Merges [closed] PRs from development into master
name: PRs to development
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
    
jobs:
  merge-dev-into-master:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge dev into master
      run: |
          git push 
